### PR TITLE
Zen 631 Mobile Drawer Icons

### PR DESCRIPTION
**Pull request by lancetipton**
**Ticket**: [ZEN-631](https://jira.simpleviewtools.com/browse/ZEN-631)

## Context
* Updated the drawer to match the new Events-Force mock-ups

## Updates
* `src/assets/icons/evf/elements/*`
  * Add Plus and Minus icons
* `src/components/grid/gridRowContent.js`
  * Switch the Drawer to use the Chevron Icon
* `src/components/textToggle/evfTextToggle.js`
  * Update to use the Plus and Minus Icons
  * Updated name of hook

## Tests
**Setup**
* Run the image =>  `keg evf pack run evf:zen-631-mobile-drawer`
* Navigate it in your browser => http://evf-zen-631-mobile-drawer.local.keghub.io/

**Test 1**
* Ensure the chevron icon displays properly on each session item
  * [Looks like this](https://i.imgur.com/cf3L1lN.png)
* Ensure it matches the mock-ups
  * [Looks like this](https://i.imgur.com/cBtC1nq.png)

**Test 2**
* Ensure the Plus and Minus icons displays properly on each session item
  * [Looks like this](https://i.imgur.com/FhMA9lK.png)
* Ensure it matches the mock-ups
  * [Looks like this](https://i.imgur.com/pH7lyEX.png)

### CODE REVIEW

**Review by mpcarolin — COMMENTED** [review]
Code looks good and behavior is right. I did notice a few minor differences from the figma mock:

The + icon looked slightly small to me, and it appears the width and height are currently set to 15 and 14 respectively. The mock has it set to 14 and 18 respectively:

image


Also the padding between the "More/Less" text and the + icon is 10 in the app, but 5 in the mockup: 

image

**Comment by lancetipton** [comment]
@mpcarolin - In reference to the Plus Icon height.
The actual height of the Icon is 14px. See this image here => https://i.imgur.com/DaWHdXs.png
  * There are 2px above and below, which gives you the 18px.
  * When converted into a SVG, those empty px are not included

**Comment by lancetipton** [comment]
This has been updated, and it ready for review again.

@mpcarolin - The Plus Icon size has been added to match the Mockups
When looking at the height and width of the Icon see this image => https://i.imgur.com/ng0AkAu.png

**Review by mpcarolin — APPROVED** [review]
Looks good

**Pull request merged**
